name: use cla workflow

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  call-shared:
    uses: luneutic/cla/.github/workflows/cla.yml@main
    permissions:
      actions: write
      contents: read
      pull-requests: write
      statuses: write
